---
version: "3.9"

x-common-variables: &common-variables
  AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID-}
  AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY-}
  HOMEPAGE_PORT: ${HOMEPAGE_PORT-3001}
  DOOR43_ENQUEUE_JOB_PROXY_PORT: ${DOOR43_ENQUEUE_JOB_PROXY_PORT-3002}
  TX_ENQUEUE_JOB_PROXY_PORT: ${TX_ENQUEUE_JOB_PROXY_PORT-3003}
  D43_CALLBACK_URL: http://d43proxy/
  DCS_PORT: ${DCS_PORT-3000}
  DCS_SSH_PORT: ${DCS_SSH_PORT-222}
  QUEUE_PREFIX: ${QUEUE_PREFIX-dev-}
  RESTRICT_DCS_URL: ${RESTRICT_DCS_URL-false}
  REDIS_HOSTNAME: ${REDIS_HOSTNAME-redis}
  DEBUG_MODE: ${DEBUG_MODE-true}
  REDIS_PORT: ${REDIS_PORT-6379}
  REDIS_URL: ${REDIS_URL-redis://redis:6379}
  DB_ENDPOINT: ${DB_ENDPOINT-sqlite:///:memory:}
  TX_DATABASE_PW: ${TX_DATABASE_PW-123}
  DCS_URL: ${DCS_URL-http://dcs}
  DCS_DOMAIN_NAME: ${DCS_DOMAIN_NAME-dcs}
  DCS_USER: ${DCS_USER-door43user}
  DCS_USER_TOKEN: ${DCS_USER_TOKEN-6a3419a11b9379ab5c8c734ef67100f7f7f90a66}
  DB_CONNECTION_STRING: ${DB_CONNECTION_STRING-sqlite:///:memory:}
  TX_POST_URL: ${TX_POST_URL-http://txproxy}
  LISTEN_IP: ${LISTEN_IP-127.0.0.1}
  ALLOWED_IPS: ${ALLOWED_IPS-0.0.0.0/0}

services:
  redis:
    container_name: redis
    environment: *common-variables
    image: redis:alpine
    ports:
      - ${LISTEN_IP:-127.0.0.1}:${REDIS_PORT-6379}:6379
    networks: 
      - tx-net

  door43-enqueue-job-proxy:
    container_name: d43proxy
    image: nginx:latest
    command: /bin/sh -c "envsubst '$$ALLOWED_IPS' < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    environment: *common-variables
    ports:
      - ${LISTEN_IP:-127.0.0.1}:${DOOR43_ENQUEUE_JOB_PROXY_PORT-3002}:80
    volumes:
      - ./door43-enqueue-job/proxyConf/dev-nginx.conf:/etc/nginx/conf.d/mysite.template:ro
    networks:
      - tx-net
    depends_on:
      - door43-enqueue-job

  door43-enqueue-job:
    container_name: door43-enqueue-job
    build:
      context: ./door43-enqueue-job/enqueue
      dockerfile: Dockerfile-developBranch
    environment: *common-variables
    volumes:
      - ./door43-enqueue-job/enqueue:/code
    networks:
      - tx-net
    depends_on:
      - redis

  door43-job-handler:
    container_name: door43-job-handler
    image: python:3
    command: /bin/bash -c "cd /scripts; pip install -r requirements.txt; rq worker --config rq_settings"
    environment: *common-variables
    volumes:
      - ./door43-job-handler:/scripts
    networks:
      - tx-net
    depends_on:
      - redis
      - tx-enqueue-job-proxy

  # door43-catalog-job-handler:
  #   container_name: door43-catalog-job-handler
  #   image: python:3
  #   command: /bin/bash -c "cd /scripts; pip install -r requirements.txt; rq worker --config rq_settings"
  #   environment: *common-variables
  #   volumes:
  #     - ./door43-catalog-job-handler:/scripts
  #   networks:
  #     - tx-net
  #   depends_on:
  #     - door43-enqueue-job-proxy

  tx-enqueue-job-proxy:
    container_name: txproxy
    image: nginx:latest
    command: /bin/sh -c "envsubst '$$ALLOWED_IPS' < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    environment: *common-variables
    ports:
      - ${LISTEN_IP:-127.0.0.1}:${TX_ENQUEUE_JOB_PROXY_PORT-3003}:80
    volumes:
      - ./tx-enqueue-job/proxyConf/dev-nginx.conf:/etc/nginx/conf.d/mysite.template:ro
    networks:
      - tx-net
    depends_on:
      - tx-enqueue-job
    
  tx-enqueue-job:
    container_name: tx-enqueue-job
    build:
      context: ./tx-enqueue-job/tXenqueue
      dockerfile: Dockerfile-developBranch
    environment: *common-variables
    volumes:
      - ./tx-enqueue-job/tXenqueue:/code
    networks:
      - tx-net
    depends_on:
      - redis

  tx-job-handler-1:
    container_name: tx-job-handler-1
    build:
      context: ./tx-job-handler
      dockerfile: Dockerfile-developBranch
    environment:
      <<: *common-variables
      WORKER_NAME: worker-1
    volumes:
      - ./tx-job-handler:/code
    networks:
      - tx-net
    depends_on:
      - redis
      - door43-enqueue-job-proxy

  tx-job-handler-2:
    container_name: tx-job-handler-2
    build:
      context: ./tx-job-handler
      dockerfile: Dockerfile-developBranch
    environment:
      <<: *common-variables
      WORKER_NAME: worker-2
    volumes:
      - ./tx-job-handler:/code
    networks:
      - tx-net
    depends_on:
      - redis
      - door43-enqueue-job-proxy

  # Need to configure your Mac OS for "dcs" https://medium.com/@anaidyonov/how-to-run-gitea-on-os-x-f5eaf726083e
  dcs:
    container_name: dcs
    build:
      context: ./tx-dev-dcs
    environment:
      - USER_UID=1000
      - USER_GID=1000
    ports:
      - ${DCS_PORT-3000}:80
      - ${DCS_SSH_PORT-222}:22
    volumes:
      - ./tx-dev-dcs/data:/data
      - ./tx-dev-dcs/app.ini:/data/gitea/conf/app.ini
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - tx-net
    depends_on:
      - door43-enqueue-job-proxy

  door43.org:
    container_name: door43.org
    build: ./door43.org
    volumes:
      - ./door43.org:/source
    ports:
      - ${LISTEN_IP:-127.0.0.1}:${DOOR43_PREVIEW_PORT-5556}:80
    networks:
      - tx-net

  homepage:
    container_name: homepage
    build: ./homepage
    environment: *common-variables
    ports:
      - ${HOMEPAGE_PORT-8080}:80
    volumes:
      - ./homepage/code:/code
      - ./homepage/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - tx-net
    links:
      - php

  php:
    container_name: php
    image: php:7-fpm
    environment: *common-variables
    volumes:
      - ./homepage/code:/code
    networks:
      - tx-net

networks:
  tx-net:
    name: tx-net
    external: false
