---
version: "3.9"

x-common-variables: &common-variables
  AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID-}
  AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY-}
  QUEUE_PREFIX: "dev-"
  RESTRICT_GITEA_URL: ${RESTRICT_GITEA_URL-false}
  REDIS_HOSTNAME: ${REDIS_HOSTNAME-redis}
  DEBUG_MODE: ${DEBUG_MODE-true}
  REDIS_URL: ${REDIS_URL-redis://redis:6379}
  DB_ENDPOINT: ${DB_ENDPOINT-sqlite:///:memory:}
  TX_DATABASE_PW: ${TX_DATABASE_PW-123}
  GITEA_URL: ${GITEA_URL-http://dcs}
  GOGS_DOMAIN_NAME: ${GOGS_DOMAIN_NAME-dcs}
  GOGS_USER: ${GOGS_USER-door43user}
  GOGS_USER_TOKEN: ${GOGS_USER_TOKEN-6a3419a11b9379ab5c8c734ef67100f7f7f90a66}
  DCS_PORT: ${DCS_PORT-5555}
  DOOR43_PREVIEW_PORT: ${DOOR43_PREVIEW_PORT-5556}
  DB_CONNECTION_STRING: ${DB_CONNECTION_STRING-sqlite:///:memory:}
  TX_POST_URL: ${TX_POST_URL-http://txproxy}

services:
  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - 6379:6379
    networks: 
      - tx-net

  d43enqueue:
    container_name: d43enqueue
    build:
      context: ./door43-enqueue-job/enqueue
      dockerfile: Dockerfile-developBranch
    environment: *common-variables
    networks:
      - tx-net
    depends_on:
      - redis

  d43proxy:
    container_name: d43proxy
    image: mohamnag/nginx-file-browser:latest
    command: /bin/sh -c "envsubst '$$ALLOWED_IPS' < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    environment:
      - ALLOWED_IPS=${ALLOWED_IPS:-0.0.0.0/0}
    volumes:
      - "${PWD}/door43-enqueue-job/proxyConf/dev-nginx.conf:/etc/nginx/conf.d/mysite.template:ro"
    networks:
      - tx-net
    depends_on:
      - d43enqueue
      
  door43-job-handler:
    image: python:3
    command: /bin/bash -c "cd /scripts; pip install -r requirements.txt; rq worker --config rq_settings"
    environment: *common-variables
    volumes:
      - ${PWD}/door43-job-handler:/scripts
      - ./door43.org/_site:/dev-door43.org
    networks:
      - tx-net
    depends_on:
      - d43proxy

  door43-catalog-job-handler:
    image: python:3
    command: /bin/bash -c "cd /scripts; pip install -r requirements.txt; rq worker --config rq_settings"
    environment: *common-variables
    volumes:
      - ${PWD}/door43-catalog-job-handler:/scripts
    networks:
      - tx-net
    depends_on:
      - d43proxy

  txenqueue:
    container_name: txenqueue
    build:
      context: ./tx-enqueue-job/tXenqueue
      dockerfile: Dockerfile-developBranch
    environment: *common-variables
    networks:
      - tx-net
    depends_on:
      - redis

  txproxy:
    container_name: txproxy
    image: mohamnag/nginx-file-browser:latest
    command: /bin/sh -c "envsubst '$$ALLOWED_IPS' < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    environment:
      - ALLOWED_IPS=${ALLOWED_IPS:-0.0.0.0/0}
    volumes:
      - ${PWD}/tx-enqueue-job/proxyConf/dev-nginx.conf:/etc/nginx/conf.d/mysite.template:ro
    networks:
      - tx-net
    depends_on:
      - txenqueue
    
  tx-job-handler:
    image: python:3
    command: /bin/bash -c "cd /scripts; pip install -r requirements.txt; rq worker --config rq_settings"
    environment: *common-variables
    volumes:
      - ${PWD}/tx-job-handler:/scripts
    networks:
      - tx-net
    depends_on:
      - txproxy

  dcs:
    container_name: dcs
    build:
      context: ./dcs
      args:
        - DOOR43_PREVIEW_PORT=${DOOR43_PREVIEW_PORT-5556}
    environment:
      - USER_UID=1000
      - USER_GID=1000
    ports:
      - ${DCS_PORT-5555}:80
      - 222:22
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - tx-net

  door43.org:
    build: ./door43.org
    volumes:
      - ./door43.org:/source
      - ./door43.org/_site:/source/_site
    ports:
      - "${LISTEN_IP:-127.0.0.1}:${DOOR43_PREVIEW_PORT-5556}:80"
    networks:
      - tx-net

  dev-door43.org:
    image: mohamnag/nginx-file-browser:latest
    volumes:
      - ./door43.org/_site:/opt/www/files
    ports:
      - "${LISTEN_IP:-127.0.0.1}:${DOOR43_CDN_PORT-5557}:80"
    networks:
      - tx-net
      
  dev-cdn.door43.org:
    image: mohamnag/nginx-file-browser:latest
    volumes:
      - ./dev-cdn.door43.org:/opt/www/files
    ports:
      - "${LISTEN_IP:-127.0.0.1}:${DOOR43_CDN_PORT-5557}:80"
    networks:
      - tx-net
      
  dev-tx-webhook-client:
    image: mohamnag/nginx-file-browser:latest
    volumes:
      - ./dev-tx-webhook-client:/opt/www/files
    ports:
      - "${LISTEN_IP:-127.0.0.1}:${DOOR43_TX_PORT-5558}:80"
    networks:
      - tx-net

networks:
  tx-net:
    name: tx-net
    external: false
